insert into `categorie_plat` (`id`, `nom_categorie`) values (1, 'Boissons');
insert into `categorie_plat` (`id`, `nom_categorie`) values (2, 'Alcool');
insert into `categorie_plat` (`id`, `nom_categorie`) values (3, 'Sans Alcool');
insert into `categorie_plat` (`id`, `nom_categorie`) values (4, 'Boissons Chaudes');
insert into `categorie_plat` (`id`, `nom_categorie`) values (5, 'Entrée');
insert into `categorie_plat` (`id`, `nom_categorie`) values (6, 'Salade');
insert into `categorie_plat` (`id`, `nom_categorie`) values (7, 'Tapas');
insert into `categorie_plat` (`id`, `nom_categorie`) values (8, 'Plat');
insert into `categorie_plat` (`id`, `nom_categorie`) values (9, 'Viandes');
insert into `categorie_plat` (`id`, `nom_categorie`) values (10, 'Poissons');
insert into `categorie_plat` (`id`, `nom_categorie`) values (11, 'Végétarien');
insert into `categorie_plat` (`id`, `nom_categorie`) values (12, 'Dessert');
